version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:6.10.0
    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/serverless-dynamodb-autoscaling/.npmrc
      - run: $(yarn bin)/dot-json package.json version ${CIRCLE_TAG:1}
      - run: npm publish
  test:
    docker:
      - image: circleci/node:6.10.0
    steps:
      - checkout
      - run: yarn lint
      - run: yarn test:cover
      - run: yarn build
      - run: yarn coveralls
        
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
